// Code generated by protoc-gen-go. DO NOT EDIT.
// source: admin.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Admin struct {
	AdminId              int64    `protobuf:"varint,1,opt,name=adminId,proto3" json:"adminId,omitempty"`
	AdminName            string   `protobuf:"bytes,2,opt,name=adminName,proto3" json:"adminName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Admin) Reset()         { *m = Admin{} }
func (m *Admin) String() string { return proto.CompactTextString(m) }
func (*Admin) ProtoMessage()    {}
func (*Admin) Descriptor() ([]byte, []int) {
	return fileDescriptor_73a7fc70dcc2027c, []int{0}
}

func (m *Admin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Admin.Unmarshal(m, b)
}
func (m *Admin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Admin.Marshal(b, m, deterministic)
}
func (m *Admin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Admin.Merge(m, src)
}
func (m *Admin) XXX_Size() int {
	return xxx_messageInfo_Admin.Size(m)
}
func (m *Admin) XXX_DiscardUnknown() {
	xxx_messageInfo_Admin.DiscardUnknown(m)
}

var xxx_messageInfo_Admin proto.InternalMessageInfo

func (m *Admin) GetAdminId() int64 {
	if m != nil {
		return m.AdminId
	}
	return 0
}

func (m *Admin) GetAdminName() string {
	if m != nil {
		return m.AdminName
	}
	return ""
}

func init() {
	proto.RegisterType((*Admin)(nil), "proto.Admin")
}

func init() {
	proto.RegisterFile("admin.proto", fileDescriptor_73a7fc70dcc2027c)
}

var fileDescriptor_73a7fc70dcc2027c = []byte{
	// 88 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x4c, 0xc9, 0xcd,
	0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xf6, 0x5c, 0xac, 0x8e,
	0x20, 0x51, 0x21, 0x09, 0x2e, 0x76, 0xb0, 0xb4, 0x67, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x73,
	0x10, 0x8c, 0x2b, 0x24, 0xc3, 0xc5, 0x09, 0x66, 0xfa, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x29, 0x30,
	0x6a, 0x70, 0x06, 0x21, 0x04, 0x92, 0xd8, 0xc0, 0xe6, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x77, 0x73, 0xeb, 0x53, 0x5d, 0x00, 0x00, 0x00,
}
