// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common "github.com/golango.cn/golden-conf/conf-proto/common"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type App struct {
	AppId                int64    `protobuf:"varint,1,opt,name=appId,proto3" json:"appId,omitempty"`
	AppCode              string   `protobuf:"bytes,2,opt,name=appCode,proto3" json:"appCode,omitempty"`
	AppDesc              string   `protobuf:"bytes,3,opt,name=appDesc,proto3" json:"appDesc,omitempty"`
	AppName              string   `protobuf:"bytes,4,opt,name=appName,proto3" json:"appName,omitempty"`
	Admin                *Admin   `protobuf:"bytes,5,opt,name=admin,proto3" json:"admin,omitempty"`
	CreateAt             int64    `protobuf:"varint,6,opt,name=createAt,proto3" json:"createAt,omitempty"`
	UpdateAt             int64    `protobuf:"varint,7,opt,name=updateAt,proto3" json:"updateAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *App) Reset()         { *m = App{} }
func (m *App) String() string { return proto.CompactTextString(m) }
func (*App) ProtoMessage()    {}
func (*App) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{0}
}

func (m *App) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_App.Unmarshal(m, b)
}
func (m *App) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_App.Marshal(b, m, deterministic)
}
func (m *App) XXX_Merge(src proto.Message) {
	xxx_messageInfo_App.Merge(m, src)
}
func (m *App) XXX_Size() int {
	return xxx_messageInfo_App.Size(m)
}
func (m *App) XXX_DiscardUnknown() {
	xxx_messageInfo_App.DiscardUnknown(m)
}

var xxx_messageInfo_App proto.InternalMessageInfo

func (m *App) GetAppId() int64 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func (m *App) GetAppCode() string {
	if m != nil {
		return m.AppCode
	}
	return ""
}

func (m *App) GetAppDesc() string {
	if m != nil {
		return m.AppDesc
	}
	return ""
}

func (m *App) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *App) GetAdmin() *Admin {
	if m != nil {
		return m.Admin
	}
	return nil
}

func (m *App) GetCreateAt() int64 {
	if m != nil {
		return m.CreateAt
	}
	return 0
}

func (m *App) GetUpdateAt() int64 {
	if m != nil {
		return m.UpdateAt
	}
	return 0
}

type GetAppRequ struct {
	BaseRequ             *common.BaseRequ `protobuf:"bytes,1,opt,name=baseRequ,proto3" json:"baseRequ,omitempty"`
	AppId                int64            `protobuf:"varint,2,opt,name=appId,proto3" json:"appId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetAppRequ) Reset()         { *m = GetAppRequ{} }
func (m *GetAppRequ) String() string { return proto.CompactTextString(m) }
func (*GetAppRequ) ProtoMessage()    {}
func (*GetAppRequ) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{1}
}

func (m *GetAppRequ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppRequ.Unmarshal(m, b)
}
func (m *GetAppRequ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppRequ.Marshal(b, m, deterministic)
}
func (m *GetAppRequ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppRequ.Merge(m, src)
}
func (m *GetAppRequ) XXX_Size() int {
	return xxx_messageInfo_GetAppRequ.Size(m)
}
func (m *GetAppRequ) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppRequ.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppRequ proto.InternalMessageInfo

func (m *GetAppRequ) GetBaseRequ() *common.BaseRequ {
	if m != nil {
		return m.BaseRequ
	}
	return nil
}

func (m *GetAppRequ) GetAppId() int64 {
	if m != nil {
		return m.AppId
	}
	return 0
}

type GetAppResp struct {
	BaseResp             *common.BaseResp `protobuf:"bytes,1,opt,name=baseResp,proto3" json:"baseResp,omitempty"`
	App                  *App             `protobuf:"bytes,2,opt,name=app,proto3" json:"app,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetAppResp) Reset()         { *m = GetAppResp{} }
func (m *GetAppResp) String() string { return proto.CompactTextString(m) }
func (*GetAppResp) ProtoMessage()    {}
func (*GetAppResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{2}
}

func (m *GetAppResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppResp.Unmarshal(m, b)
}
func (m *GetAppResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppResp.Marshal(b, m, deterministic)
}
func (m *GetAppResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppResp.Merge(m, src)
}
func (m *GetAppResp) XXX_Size() int {
	return xxx_messageInfo_GetAppResp.Size(m)
}
func (m *GetAppResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppResp proto.InternalMessageInfo

func (m *GetAppResp) GetBaseResp() *common.BaseResp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

func (m *GetAppResp) GetApp() *App {
	if m != nil {
		return m.App
	}
	return nil
}

type GetAppsRequ struct {
	BaseRequ             *common.BaseRequ `protobuf:"bytes,1,opt,name=baseRequ,proto3" json:"baseRequ,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetAppsRequ) Reset()         { *m = GetAppsRequ{} }
func (m *GetAppsRequ) String() string { return proto.CompactTextString(m) }
func (*GetAppsRequ) ProtoMessage()    {}
func (*GetAppsRequ) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{3}
}

func (m *GetAppsRequ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppsRequ.Unmarshal(m, b)
}
func (m *GetAppsRequ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppsRequ.Marshal(b, m, deterministic)
}
func (m *GetAppsRequ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppsRequ.Merge(m, src)
}
func (m *GetAppsRequ) XXX_Size() int {
	return xxx_messageInfo_GetAppsRequ.Size(m)
}
func (m *GetAppsRequ) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppsRequ.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppsRequ proto.InternalMessageInfo

func (m *GetAppsRequ) GetBaseRequ() *common.BaseRequ {
	if m != nil {
		return m.BaseRequ
	}
	return nil
}

type GetAppsResp struct {
	BaseResp             *common.BaseResp `protobuf:"bytes,1,opt,name=baseResp,proto3" json:"baseResp,omitempty"`
	Apps                 []*App           `protobuf:"bytes,2,rep,name=apps,proto3" json:"apps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetAppsResp) Reset()         { *m = GetAppsResp{} }
func (m *GetAppsResp) String() string { return proto.CompactTextString(m) }
func (*GetAppsResp) ProtoMessage()    {}
func (*GetAppsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{4}
}

func (m *GetAppsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppsResp.Unmarshal(m, b)
}
func (m *GetAppsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppsResp.Marshal(b, m, deterministic)
}
func (m *GetAppsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppsResp.Merge(m, src)
}
func (m *GetAppsResp) XXX_Size() int {
	return xxx_messageInfo_GetAppsResp.Size(m)
}
func (m *GetAppsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppsResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppsResp proto.InternalMessageInfo

func (m *GetAppsResp) GetBaseResp() *common.BaseResp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

func (m *GetAppsResp) GetApps() []*App {
	if m != nil {
		return m.Apps
	}
	return nil
}

type CreateAppRequ struct {
	BaseRequ             *common.BaseRequ `protobuf:"bytes,1,opt,name=baseRequ,proto3" json:"baseRequ,omitempty"`
	App                  *App             `protobuf:"bytes,2,opt,name=app,proto3" json:"app,omitempty"`
	Environments         []string         `protobuf:"bytes,3,rep,name=environments,proto3" json:"environments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CreateAppRequ) Reset()         { *m = CreateAppRequ{} }
func (m *CreateAppRequ) String() string { return proto.CompactTextString(m) }
func (*CreateAppRequ) ProtoMessage()    {}
func (*CreateAppRequ) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{5}
}

func (m *CreateAppRequ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAppRequ.Unmarshal(m, b)
}
func (m *CreateAppRequ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAppRequ.Marshal(b, m, deterministic)
}
func (m *CreateAppRequ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAppRequ.Merge(m, src)
}
func (m *CreateAppRequ) XXX_Size() int {
	return xxx_messageInfo_CreateAppRequ.Size(m)
}
func (m *CreateAppRequ) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAppRequ.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAppRequ proto.InternalMessageInfo

func (m *CreateAppRequ) GetBaseRequ() *common.BaseRequ {
	if m != nil {
		return m.BaseRequ
	}
	return nil
}

func (m *CreateAppRequ) GetApp() *App {
	if m != nil {
		return m.App
	}
	return nil
}

func (m *CreateAppRequ) GetEnvironments() []string {
	if m != nil {
		return m.Environments
	}
	return nil
}

type CreateAppResp struct {
	BaseResp             *common.BaseResp `protobuf:"bytes,1,opt,name=baseResp,proto3" json:"baseResp,omitempty"`
	AppId                int64            `protobuf:"varint,2,opt,name=appId,proto3" json:"appId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CreateAppResp) Reset()         { *m = CreateAppResp{} }
func (m *CreateAppResp) String() string { return proto.CompactTextString(m) }
func (*CreateAppResp) ProtoMessage()    {}
func (*CreateAppResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{6}
}

func (m *CreateAppResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAppResp.Unmarshal(m, b)
}
func (m *CreateAppResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAppResp.Marshal(b, m, deterministic)
}
func (m *CreateAppResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAppResp.Merge(m, src)
}
func (m *CreateAppResp) XXX_Size() int {
	return xxx_messageInfo_CreateAppResp.Size(m)
}
func (m *CreateAppResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAppResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAppResp proto.InternalMessageInfo

func (m *CreateAppResp) GetBaseResp() *common.BaseResp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

func (m *CreateAppResp) GetAppId() int64 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func init() {
	proto.RegisterType((*App)(nil), "proto.App")
	proto.RegisterType((*GetAppRequ)(nil), "proto.GetAppRequ")
	proto.RegisterType((*GetAppResp)(nil), "proto.GetAppResp")
	proto.RegisterType((*GetAppsRequ)(nil), "proto.GetAppsRequ")
	proto.RegisterType((*GetAppsResp)(nil), "proto.GetAppsResp")
	proto.RegisterType((*CreateAppRequ)(nil), "proto.CreateAppRequ")
	proto.RegisterType((*CreateAppResp)(nil), "proto.CreateAppResp")
}

func init() {
	proto.RegisterFile("app.proto", fileDescriptor_e0f9056a14b86d47)
}

var fileDescriptor_e0f9056a14b86d47 = []byte{
	// 422 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x4d, 0x8b, 0xd4, 0x40,
	0x10, 0x35, 0x93, 0x9d, 0x99, 0x4d, 0x65, 0x05, 0x6d, 0xf6, 0xd0, 0x04, 0x91, 0xd0, 0xa7, 0x39,
	0xb8, 0x89, 0x64, 0x4f, 0x22, 0x08, 0x61, 0x05, 0xf1, 0x22, 0xd2, 0x7b, 0x11, 0x3c, 0xf5, 0x24,
	0xed, 0x38, 0x60, 0xba, 0xcb, 0x74, 0x66, 0xaf, 0xfe, 0x22, 0x7f, 0x86, 0xff, 0x4b, 0xba, 0x3b,
	0x1f, 0x9b, 0x75, 0x10, 0x66, 0x2f, 0x49, 0xbf, 0xf7, 0xaa, 0x2a, 0xef, 0x55, 0x07, 0x22, 0x81,
	0x98, 0x61, 0xab, 0x3b, 0x4d, 0x96, 0xee, 0x95, 0xbc, 0xdb, 0xed, 0xbb, 0xef, 0x87, 0x6d, 0x56,
	0xe9, 0x26, 0xdf, 0xe9, 0x1f, 0x42, 0xed, 0x74, 0x56, 0x29, 0x7b, 0xac, 0xa5, 0xba, 0xaa, 0xb4,
	0xfa, 0x96, 0xdb, 0xc7, 0x95, 0xab, 0xce, 0x2b, 0xdd, 0x34, 0x5a, 0xe5, 0x5b, 0x61, 0xa4, 0x1f,
	0x93, 0xc4, 0xa2, 0x6e, 0xf6, 0xca, 0x03, 0xf6, 0x27, 0x80, 0xb0, 0x44, 0x24, 0x97, 0xb0, 0x14,
	0x88, 0x1f, 0x6b, 0x1a, 0xa4, 0xc1, 0x26, 0xe4, 0x1e, 0x10, 0x0a, 0x6b, 0x81, 0x78, 0xa3, 0x6b,
	0x49, 0x17, 0x69, 0xb0, 0x89, 0xf8, 0x00, 0x7b, 0xe5, 0xbd, 0x34, 0x15, 0x0d, 0x47, 0xc5, 0xc2,
	0x5e, 0xf9, 0x24, 0x1a, 0x49, 0xcf, 0x46, 0xc5, 0x42, 0xc2, 0x60, 0xe9, 0x3e, 0x4d, 0x97, 0x69,
	0xb0, 0x89, 0x8b, 0x0b, 0x6f, 0x21, 0x2b, 0x2d, 0xc7, 0xbd, 0x44, 0x12, 0x38, 0xaf, 0x5a, 0x29,
	0x3a, 0x59, 0x76, 0x74, 0xe5, 0xac, 0x8c, 0xd8, 0x6a, 0x07, 0xac, 0xbd, 0xb6, 0xf6, 0xda, 0x80,
	0xd9, 0x67, 0x80, 0x0f, 0xb2, 0x2b, 0x11, 0xb9, 0xfc, 0x79, 0x20, 0xaf, 0xe0, 0xdc, 0x06, 0xb6,
	0x67, 0x17, 0x28, 0x2e, 0x9e, 0x65, 0x7e, 0x11, 0xd9, 0xc0, 0xf3, 0xb1, 0x62, 0xca, 0xbe, 0xb8,
	0x97, 0x9d, 0x7d, 0x99, 0x26, 0x1a, 0x9c, 0x26, 0x1a, 0x3c, 0x3e, 0xd1, 0x20, 0x1f, 0x2b, 0xc8,
	0x0b, 0x08, 0x05, 0xa2, 0x9b, 0x17, 0x17, 0x30, 0xe4, 0x44, 0xe4, 0x96, 0x66, 0x6f, 0x21, 0xf6,
	0x93, 0xcd, 0xe9, 0x66, 0xd9, 0xd7, 0x7b, 0xcd, 0x27, 0xfb, 0x7a, 0x09, 0x67, 0x02, 0xd1, 0xd0,
	0x45, 0x1a, 0x3e, 0x30, 0xe6, 0x78, 0xf6, 0x0b, 0x9e, 0xde, 0xf8, 0x6d, 0x3f, 0x6a, 0x91, 0xff,
	0x8d, 0x4d, 0x18, 0x5c, 0x48, 0x75, 0xb7, 0x6f, 0xb5, 0x6a, 0xa4, 0xea, 0x0c, 0x0d, 0xd3, 0x70,
	0x13, 0xf1, 0x19, 0xc7, 0x6e, 0x67, 0x06, 0x4e, 0xce, 0x77, 0xf4, 0x26, 0x8b, 0xdf, 0x01, 0x44,
	0x25, 0xe2, 0xad, 0x6c, 0xef, 0x64, 0x4b, 0x5e, 0xc3, 0xca, 0x2f, 0x90, 0x3c, 0xef, 0x1d, 0x4e,
	0x3f, 0x4e, 0xf2, 0x90, 0x32, 0xc8, 0x9e, 0x90, 0x6b, 0x58, 0xf7, 0x2b, 0x27, 0x64, 0xa6, 0xbb,
	0xfb, 0x4b, 0xfe, 0xe1, 0x5c, 0xd3, 0x1b, 0x88, 0xc6, 0x24, 0xe4, 0xb2, 0x2f, 0x99, 0x2d, 0x37,
	0x39, 0xc2, 0xda, 0xd6, 0xed, 0xca, 0xd1, 0xd7, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x68, 0x3c,
	0x96, 0xb6, 0xfb, 0x03, 0x00, 0x00,
}
