// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common "github.com/golango.cn/golden-conf/conf-proto/common"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetConfigRequ struct {
	BaseRequ             *common.BaseRequ `protobuf:"bytes,1,opt,name=baseRequ,proto3" json:"baseRequ,omitempty"`
	AppConfigId          int64            `protobuf:"varint,2,opt,name=appConfigId,proto3" json:"appConfigId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetConfigRequ) Reset()         { *m = GetConfigRequ{} }
func (m *GetConfigRequ) String() string { return proto.CompactTextString(m) }
func (*GetConfigRequ) ProtoMessage()    {}
func (*GetConfigRequ) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{0}
}

func (m *GetConfigRequ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigRequ.Unmarshal(m, b)
}
func (m *GetConfigRequ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigRequ.Marshal(b, m, deterministic)
}
func (m *GetConfigRequ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigRequ.Merge(m, src)
}
func (m *GetConfigRequ) XXX_Size() int {
	return xxx_messageInfo_GetConfigRequ.Size(m)
}
func (m *GetConfigRequ) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigRequ.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigRequ proto.InternalMessageInfo

func (m *GetConfigRequ) GetBaseRequ() *common.BaseRequ {
	if m != nil {
		return m.BaseRequ
	}
	return nil
}

func (m *GetConfigRequ) GetAppConfigId() int64 {
	if m != nil {
		return m.AppConfigId
	}
	return 0
}

type GetConfigResp struct {
	BaseResp             *common.BaseResp `protobuf:"bytes,1,opt,name=baseResp,proto3" json:"baseResp,omitempty"`
	AppConfig            *AppConfig       `protobuf:"bytes,2,opt,name=appConfig,proto3" json:"appConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetConfigResp) Reset()         { *m = GetConfigResp{} }
func (m *GetConfigResp) String() string { return proto.CompactTextString(m) }
func (*GetConfigResp) ProtoMessage()    {}
func (*GetConfigResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{1}
}

func (m *GetConfigResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigResp.Unmarshal(m, b)
}
func (m *GetConfigResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigResp.Marshal(b, m, deterministic)
}
func (m *GetConfigResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigResp.Merge(m, src)
}
func (m *GetConfigResp) XXX_Size() int {
	return xxx_messageInfo_GetConfigResp.Size(m)
}
func (m *GetConfigResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigResp proto.InternalMessageInfo

func (m *GetConfigResp) GetBaseResp() *common.BaseResp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

func (m *GetConfigResp) GetAppConfig() *AppConfig {
	if m != nil {
		return m.AppConfig
	}
	return nil
}

type GetAppConfigsRequ struct {
	BaseRequ             *common.BaseRequ `protobuf:"bytes,1,opt,name=baseRequ,proto3" json:"baseRequ,omitempty"`
	Key                  string           `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	AppCode              string           `protobuf:"bytes,3,opt,name=appCode,proto3" json:"appCode,omitempty"`
	EnvironmentName      string           `protobuf:"bytes,4,opt,name=environmentName,proto3" json:"environmentName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetAppConfigsRequ) Reset()         { *m = GetAppConfigsRequ{} }
func (m *GetAppConfigsRequ) String() string { return proto.CompactTextString(m) }
func (*GetAppConfigsRequ) ProtoMessage()    {}
func (*GetAppConfigsRequ) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{2}
}

func (m *GetAppConfigsRequ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppConfigsRequ.Unmarshal(m, b)
}
func (m *GetAppConfigsRequ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppConfigsRequ.Marshal(b, m, deterministic)
}
func (m *GetAppConfigsRequ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppConfigsRequ.Merge(m, src)
}
func (m *GetAppConfigsRequ) XXX_Size() int {
	return xxx_messageInfo_GetAppConfigsRequ.Size(m)
}
func (m *GetAppConfigsRequ) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppConfigsRequ.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppConfigsRequ proto.InternalMessageInfo

func (m *GetAppConfigsRequ) GetBaseRequ() *common.BaseRequ {
	if m != nil {
		return m.BaseRequ
	}
	return nil
}

func (m *GetAppConfigsRequ) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetAppConfigsRequ) GetAppCode() string {
	if m != nil {
		return m.AppCode
	}
	return ""
}

func (m *GetAppConfigsRequ) GetEnvironmentName() string {
	if m != nil {
		return m.EnvironmentName
	}
	return ""
}

type GetAppConfigsResp struct {
	BaseResp             *common.BaseResp `protobuf:"bytes,1,opt,name=baseResp,proto3" json:"baseResp,omitempty"`
	AppConfigs           []*AppConfig     `protobuf:"bytes,2,rep,name=appConfigs,proto3" json:"appConfigs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetAppConfigsResp) Reset()         { *m = GetAppConfigsResp{} }
func (m *GetAppConfigsResp) String() string { return proto.CompactTextString(m) }
func (*GetAppConfigsResp) ProtoMessage()    {}
func (*GetAppConfigsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{3}
}

func (m *GetAppConfigsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppConfigsResp.Unmarshal(m, b)
}
func (m *GetAppConfigsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppConfigsResp.Marshal(b, m, deterministic)
}
func (m *GetAppConfigsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppConfigsResp.Merge(m, src)
}
func (m *GetAppConfigsResp) XXX_Size() int {
	return xxx_messageInfo_GetAppConfigsResp.Size(m)
}
func (m *GetAppConfigsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppConfigsResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppConfigsResp proto.InternalMessageInfo

func (m *GetAppConfigsResp) GetBaseResp() *common.BaseResp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

func (m *GetAppConfigsResp) GetAppConfigs() []*AppConfig {
	if m != nil {
		return m.AppConfigs
	}
	return nil
}

type CreateAppConfigRequ struct {
	BaseRequ             *common.BaseRequ `protobuf:"bytes,1,opt,name=baseRequ,proto3" json:"baseRequ,omitempty"`
	AppConfig            *AppConfig       `protobuf:"bytes,2,opt,name=appConfig,proto3" json:"appConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CreateAppConfigRequ) Reset()         { *m = CreateAppConfigRequ{} }
func (m *CreateAppConfigRequ) String() string { return proto.CompactTextString(m) }
func (*CreateAppConfigRequ) ProtoMessage()    {}
func (*CreateAppConfigRequ) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{4}
}

func (m *CreateAppConfigRequ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAppConfigRequ.Unmarshal(m, b)
}
func (m *CreateAppConfigRequ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAppConfigRequ.Marshal(b, m, deterministic)
}
func (m *CreateAppConfigRequ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAppConfigRequ.Merge(m, src)
}
func (m *CreateAppConfigRequ) XXX_Size() int {
	return xxx_messageInfo_CreateAppConfigRequ.Size(m)
}
func (m *CreateAppConfigRequ) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAppConfigRequ.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAppConfigRequ proto.InternalMessageInfo

func (m *CreateAppConfigRequ) GetBaseRequ() *common.BaseRequ {
	if m != nil {
		return m.BaseRequ
	}
	return nil
}

func (m *CreateAppConfigRequ) GetAppConfig() *AppConfig {
	if m != nil {
		return m.AppConfig
	}
	return nil
}

type CreateAppConfigResp struct {
	BaseResp             *common.BaseResp `protobuf:"bytes,1,opt,name=baseResp,proto3" json:"baseResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CreateAppConfigResp) Reset()         { *m = CreateAppConfigResp{} }
func (m *CreateAppConfigResp) String() string { return proto.CompactTextString(m) }
func (*CreateAppConfigResp) ProtoMessage()    {}
func (*CreateAppConfigResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{5}
}

func (m *CreateAppConfigResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAppConfigResp.Unmarshal(m, b)
}
func (m *CreateAppConfigResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAppConfigResp.Marshal(b, m, deterministic)
}
func (m *CreateAppConfigResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAppConfigResp.Merge(m, src)
}
func (m *CreateAppConfigResp) XXX_Size() int {
	return xxx_messageInfo_CreateAppConfigResp.Size(m)
}
func (m *CreateAppConfigResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAppConfigResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAppConfigResp proto.InternalMessageInfo

func (m *CreateAppConfigResp) GetBaseResp() *common.BaseResp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

type UpdateAppConfigRequ struct {
	BaseRequ             *common.BaseRequ `protobuf:"bytes,1,opt,name=baseRequ,proto3" json:"baseRequ,omitempty"`
	AppConfig            *AppConfig       `protobuf:"bytes,2,opt,name=appConfig,proto3" json:"appConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UpdateAppConfigRequ) Reset()         { *m = UpdateAppConfigRequ{} }
func (m *UpdateAppConfigRequ) String() string { return proto.CompactTextString(m) }
func (*UpdateAppConfigRequ) ProtoMessage()    {}
func (*UpdateAppConfigRequ) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{6}
}

func (m *UpdateAppConfigRequ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAppConfigRequ.Unmarshal(m, b)
}
func (m *UpdateAppConfigRequ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAppConfigRequ.Marshal(b, m, deterministic)
}
func (m *UpdateAppConfigRequ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAppConfigRequ.Merge(m, src)
}
func (m *UpdateAppConfigRequ) XXX_Size() int {
	return xxx_messageInfo_UpdateAppConfigRequ.Size(m)
}
func (m *UpdateAppConfigRequ) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAppConfigRequ.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAppConfigRequ proto.InternalMessageInfo

func (m *UpdateAppConfigRequ) GetBaseRequ() *common.BaseRequ {
	if m != nil {
		return m.BaseRequ
	}
	return nil
}

func (m *UpdateAppConfigRequ) GetAppConfig() *AppConfig {
	if m != nil {
		return m.AppConfig
	}
	return nil
}

type UpdateAppConfigResp struct {
	BaseResp             *common.BaseResp `protobuf:"bytes,1,opt,name=baseResp,proto3" json:"baseResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UpdateAppConfigResp) Reset()         { *m = UpdateAppConfigResp{} }
func (m *UpdateAppConfigResp) String() string { return proto.CompactTextString(m) }
func (*UpdateAppConfigResp) ProtoMessage()    {}
func (*UpdateAppConfigResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{7}
}

func (m *UpdateAppConfigResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAppConfigResp.Unmarshal(m, b)
}
func (m *UpdateAppConfigResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAppConfigResp.Marshal(b, m, deterministic)
}
func (m *UpdateAppConfigResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAppConfigResp.Merge(m, src)
}
func (m *UpdateAppConfigResp) XXX_Size() int {
	return xxx_messageInfo_UpdateAppConfigResp.Size(m)
}
func (m *UpdateAppConfigResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAppConfigResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAppConfigResp proto.InternalMessageInfo

func (m *UpdateAppConfigResp) GetBaseResp() *common.BaseResp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

type GetAppConfigHistorysRequ struct {
	BaseRequ             *common.BaseRequ `protobuf:"bytes,1,opt,name=baseRequ,proto3" json:"baseRequ,omitempty"`
	AppConfigId          int64            `protobuf:"varint,2,opt,name=appConfigId,proto3" json:"appConfigId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetAppConfigHistorysRequ) Reset()         { *m = GetAppConfigHistorysRequ{} }
func (m *GetAppConfigHistorysRequ) String() string { return proto.CompactTextString(m) }
func (*GetAppConfigHistorysRequ) ProtoMessage()    {}
func (*GetAppConfigHistorysRequ) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{8}
}

func (m *GetAppConfigHistorysRequ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppConfigHistorysRequ.Unmarshal(m, b)
}
func (m *GetAppConfigHistorysRequ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppConfigHistorysRequ.Marshal(b, m, deterministic)
}
func (m *GetAppConfigHistorysRequ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppConfigHistorysRequ.Merge(m, src)
}
func (m *GetAppConfigHistorysRequ) XXX_Size() int {
	return xxx_messageInfo_GetAppConfigHistorysRequ.Size(m)
}
func (m *GetAppConfigHistorysRequ) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppConfigHistorysRequ.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppConfigHistorysRequ proto.InternalMessageInfo

func (m *GetAppConfigHistorysRequ) GetBaseRequ() *common.BaseRequ {
	if m != nil {
		return m.BaseRequ
	}
	return nil
}

func (m *GetAppConfigHistorysRequ) GetAppConfigId() int64 {
	if m != nil {
		return m.AppConfigId
	}
	return 0
}

type GetAppConfigHistorysResp struct {
	BaseResp             *common.BaseResp    `protobuf:"bytes,1,opt,name=baseResp,proto3" json:"baseResp,omitempty"`
	AppConfigHistorys    []*AppConfigHistory `protobuf:"bytes,2,rep,name=appConfigHistorys,proto3" json:"appConfigHistorys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetAppConfigHistorysResp) Reset()         { *m = GetAppConfigHistorysResp{} }
func (m *GetAppConfigHistorysResp) String() string { return proto.CompactTextString(m) }
func (*GetAppConfigHistorysResp) ProtoMessage()    {}
func (*GetAppConfigHistorysResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{9}
}

func (m *GetAppConfigHistorysResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppConfigHistorysResp.Unmarshal(m, b)
}
func (m *GetAppConfigHistorysResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppConfigHistorysResp.Marshal(b, m, deterministic)
}
func (m *GetAppConfigHistorysResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppConfigHistorysResp.Merge(m, src)
}
func (m *GetAppConfigHistorysResp) XXX_Size() int {
	return xxx_messageInfo_GetAppConfigHistorysResp.Size(m)
}
func (m *GetAppConfigHistorysResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppConfigHistorysResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppConfigHistorysResp proto.InternalMessageInfo

func (m *GetAppConfigHistorysResp) GetBaseResp() *common.BaseResp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

func (m *GetAppConfigHistorysResp) GetAppConfigHistorys() []*AppConfigHistory {
	if m != nil {
		return m.AppConfigHistorys
	}
	return nil
}

type RollbackConfigRequ struct {
	BaseRequ             *common.BaseRequ `protobuf:"bytes,1,opt,name=baseRequ,proto3" json:"baseRequ,omitempty"`
	AppConfigHistoryId   int64            `protobuf:"varint,2,opt,name=appConfigHistoryId,proto3" json:"appConfigHistoryId,omitempty"`
	AdminId              int64            `protobuf:"varint,3,opt,name=adminId,proto3" json:"adminId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RollbackConfigRequ) Reset()         { *m = RollbackConfigRequ{} }
func (m *RollbackConfigRequ) String() string { return proto.CompactTextString(m) }
func (*RollbackConfigRequ) ProtoMessage()    {}
func (*RollbackConfigRequ) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{10}
}

func (m *RollbackConfigRequ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RollbackConfigRequ.Unmarshal(m, b)
}
func (m *RollbackConfigRequ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RollbackConfigRequ.Marshal(b, m, deterministic)
}
func (m *RollbackConfigRequ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollbackConfigRequ.Merge(m, src)
}
func (m *RollbackConfigRequ) XXX_Size() int {
	return xxx_messageInfo_RollbackConfigRequ.Size(m)
}
func (m *RollbackConfigRequ) XXX_DiscardUnknown() {
	xxx_messageInfo_RollbackConfigRequ.DiscardUnknown(m)
}

var xxx_messageInfo_RollbackConfigRequ proto.InternalMessageInfo

func (m *RollbackConfigRequ) GetBaseRequ() *common.BaseRequ {
	if m != nil {
		return m.BaseRequ
	}
	return nil
}

func (m *RollbackConfigRequ) GetAppConfigHistoryId() int64 {
	if m != nil {
		return m.AppConfigHistoryId
	}
	return 0
}

func (m *RollbackConfigRequ) GetAdminId() int64 {
	if m != nil {
		return m.AdminId
	}
	return 0
}

type RollbackConfigResp struct {
	BaseResp             *common.BaseResp `protobuf:"bytes,1,opt,name=baseResp,proto3" json:"baseResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RollbackConfigResp) Reset()         { *m = RollbackConfigResp{} }
func (m *RollbackConfigResp) String() string { return proto.CompactTextString(m) }
func (*RollbackConfigResp) ProtoMessage()    {}
func (*RollbackConfigResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{11}
}

func (m *RollbackConfigResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RollbackConfigResp.Unmarshal(m, b)
}
func (m *RollbackConfigResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RollbackConfigResp.Marshal(b, m, deterministic)
}
func (m *RollbackConfigResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollbackConfigResp.Merge(m, src)
}
func (m *RollbackConfigResp) XXX_Size() int {
	return xxx_messageInfo_RollbackConfigResp.Size(m)
}
func (m *RollbackConfigResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RollbackConfigResp.DiscardUnknown(m)
}

var xxx_messageInfo_RollbackConfigResp proto.InternalMessageInfo

func (m *RollbackConfigResp) GetBaseResp() *common.BaseResp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

type PublicConfigRequ struct {
	BaseRequ             *common.BaseRequ `protobuf:"bytes,1,opt,name=baseRequ,proto3" json:"baseRequ,omitempty"`
	AppConfigId          int64            `protobuf:"varint,2,opt,name=appConfigId,proto3" json:"appConfigId,omitempty"`
	AdminId              int64            `protobuf:"varint,3,opt,name=adminId,proto3" json:"adminId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PublicConfigRequ) Reset()         { *m = PublicConfigRequ{} }
func (m *PublicConfigRequ) String() string { return proto.CompactTextString(m) }
func (*PublicConfigRequ) ProtoMessage()    {}
func (*PublicConfigRequ) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{12}
}

func (m *PublicConfigRequ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicConfigRequ.Unmarshal(m, b)
}
func (m *PublicConfigRequ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicConfigRequ.Marshal(b, m, deterministic)
}
func (m *PublicConfigRequ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicConfigRequ.Merge(m, src)
}
func (m *PublicConfigRequ) XXX_Size() int {
	return xxx_messageInfo_PublicConfigRequ.Size(m)
}
func (m *PublicConfigRequ) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicConfigRequ.DiscardUnknown(m)
}

var xxx_messageInfo_PublicConfigRequ proto.InternalMessageInfo

func (m *PublicConfigRequ) GetBaseRequ() *common.BaseRequ {
	if m != nil {
		return m.BaseRequ
	}
	return nil
}

func (m *PublicConfigRequ) GetAppConfigId() int64 {
	if m != nil {
		return m.AppConfigId
	}
	return 0
}

func (m *PublicConfigRequ) GetAdminId() int64 {
	if m != nil {
		return m.AdminId
	}
	return 0
}

type PublicConfigResp struct {
	BaseResp             *common.BaseResp `protobuf:"bytes,1,opt,name=baseResp,proto3" json:"baseResp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PublicConfigResp) Reset()         { *m = PublicConfigResp{} }
func (m *PublicConfigResp) String() string { return proto.CompactTextString(m) }
func (*PublicConfigResp) ProtoMessage()    {}
func (*PublicConfigResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{13}
}

func (m *PublicConfigResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicConfigResp.Unmarshal(m, b)
}
func (m *PublicConfigResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicConfigResp.Marshal(b, m, deterministic)
}
func (m *PublicConfigResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicConfigResp.Merge(m, src)
}
func (m *PublicConfigResp) XXX_Size() int {
	return xxx_messageInfo_PublicConfigResp.Size(m)
}
func (m *PublicConfigResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicConfigResp.DiscardUnknown(m)
}

var xxx_messageInfo_PublicConfigResp proto.InternalMessageInfo

func (m *PublicConfigResp) GetBaseResp() *common.BaseResp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

type AppConfig struct {
	AppConfigId          int64    `protobuf:"varint,1,opt,name=appConfigId,proto3" json:"appConfigId,omitempty"`
	AppId                int64    `protobuf:"varint,2,opt,name=appId,proto3" json:"appId,omitempty"`
	AppCode              string   `protobuf:"bytes,3,opt,name=appCode,proto3" json:"appCode,omitempty"`
	EnvironmentName      string   `protobuf:"bytes,4,opt,name=environmentName,proto3" json:"environmentName,omitempty"`
	Key                  string   `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	Status               int64    `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	Memo                 string   `protobuf:"bytes,8,opt,name=memo,proto3" json:"memo,omitempty"`
	Admin                *Admin   `protobuf:"bytes,9,opt,name=admin,proto3" json:"admin,omitempty"`
	CreateAt             int64    `protobuf:"varint,10,opt,name=createAt,proto3" json:"createAt,omitempty"`
	UpdateAt             int64    `protobuf:"varint,11,opt,name=updateAt,proto3" json:"updateAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppConfig) Reset()         { *m = AppConfig{} }
func (m *AppConfig) String() string { return proto.CompactTextString(m) }
func (*AppConfig) ProtoMessage()    {}
func (*AppConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{14}
}

func (m *AppConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppConfig.Unmarshal(m, b)
}
func (m *AppConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppConfig.Marshal(b, m, deterministic)
}
func (m *AppConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppConfig.Merge(m, src)
}
func (m *AppConfig) XXX_Size() int {
	return xxx_messageInfo_AppConfig.Size(m)
}
func (m *AppConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_AppConfig.DiscardUnknown(m)
}

var xxx_messageInfo_AppConfig proto.InternalMessageInfo

func (m *AppConfig) GetAppConfigId() int64 {
	if m != nil {
		return m.AppConfigId
	}
	return 0
}

func (m *AppConfig) GetAppId() int64 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func (m *AppConfig) GetAppCode() string {
	if m != nil {
		return m.AppCode
	}
	return ""
}

func (m *AppConfig) GetEnvironmentName() string {
	if m != nil {
		return m.EnvironmentName
	}
	return ""
}

func (m *AppConfig) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *AppConfig) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *AppConfig) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AppConfig) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *AppConfig) GetAdmin() *Admin {
	if m != nil {
		return m.Admin
	}
	return nil
}

func (m *AppConfig) GetCreateAt() int64 {
	if m != nil {
		return m.CreateAt
	}
	return 0
}

func (m *AppConfig) GetUpdateAt() int64 {
	if m != nil {
		return m.UpdateAt
	}
	return 0
}

type AppConfigHistory struct {
	AppConfigHistoryId   int64    `protobuf:"varint,1,opt,name=appConfigHistoryId,proto3" json:"appConfigHistoryId,omitempty"`
	AppConfigId          int64    `protobuf:"varint,2,opt,name=appConfigId,proto3" json:"appConfigId,omitempty"`
	AppId                int64    `protobuf:"varint,3,opt,name=appId,proto3" json:"appId,omitempty"`
	AppCode              string   `protobuf:"bytes,4,opt,name=appCode,proto3" json:"appCode,omitempty"`
	EnvironmentName      string   `protobuf:"bytes,5,opt,name=environmentName,proto3" json:"environmentName,omitempty"`
	Key                  string   `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
	Status               int64    `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	Memo                 string   `protobuf:"bytes,9,opt,name=memo,proto3" json:"memo,omitempty"`
	Admin                *Admin   `protobuf:"bytes,10,opt,name=admin,proto3" json:"admin,omitempty"`
	CreateAt             int64    `protobuf:"varint,11,opt,name=createAt,proto3" json:"createAt,omitempty"`
	UpdateAt             int64    `protobuf:"varint,12,opt,name=updateAt,proto3" json:"updateAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppConfigHistory) Reset()         { *m = AppConfigHistory{} }
func (m *AppConfigHistory) String() string { return proto.CompactTextString(m) }
func (*AppConfigHistory) ProtoMessage()    {}
func (*AppConfigHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{15}
}

func (m *AppConfigHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppConfigHistory.Unmarshal(m, b)
}
func (m *AppConfigHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppConfigHistory.Marshal(b, m, deterministic)
}
func (m *AppConfigHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppConfigHistory.Merge(m, src)
}
func (m *AppConfigHistory) XXX_Size() int {
	return xxx_messageInfo_AppConfigHistory.Size(m)
}
func (m *AppConfigHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_AppConfigHistory.DiscardUnknown(m)
}

var xxx_messageInfo_AppConfigHistory proto.InternalMessageInfo

func (m *AppConfigHistory) GetAppConfigHistoryId() int64 {
	if m != nil {
		return m.AppConfigHistoryId
	}
	return 0
}

func (m *AppConfigHistory) GetAppConfigId() int64 {
	if m != nil {
		return m.AppConfigId
	}
	return 0
}

func (m *AppConfigHistory) GetAppId() int64 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func (m *AppConfigHistory) GetAppCode() string {
	if m != nil {
		return m.AppCode
	}
	return ""
}

func (m *AppConfigHistory) GetEnvironmentName() string {
	if m != nil {
		return m.EnvironmentName
	}
	return ""
}

func (m *AppConfigHistory) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *AppConfigHistory) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *AppConfigHistory) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AppConfigHistory) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *AppConfigHistory) GetAdmin() *Admin {
	if m != nil {
		return m.Admin
	}
	return nil
}

func (m *AppConfigHistory) GetCreateAt() int64 {
	if m != nil {
		return m.CreateAt
	}
	return 0
}

func (m *AppConfigHistory) GetUpdateAt() int64 {
	if m != nil {
		return m.UpdateAt
	}
	return 0
}

func init() {
	proto.RegisterType((*GetConfigRequ)(nil), "proto.GetConfigRequ")
	proto.RegisterType((*GetConfigResp)(nil), "proto.GetConfigResp")
	proto.RegisterType((*GetAppConfigsRequ)(nil), "proto.GetAppConfigsRequ")
	proto.RegisterType((*GetAppConfigsResp)(nil), "proto.GetAppConfigsResp")
	proto.RegisterType((*CreateAppConfigRequ)(nil), "proto.CreateAppConfigRequ")
	proto.RegisterType((*CreateAppConfigResp)(nil), "proto.CreateAppConfigResp")
	proto.RegisterType((*UpdateAppConfigRequ)(nil), "proto.UpdateAppConfigRequ")
	proto.RegisterType((*UpdateAppConfigResp)(nil), "proto.UpdateAppConfigResp")
	proto.RegisterType((*GetAppConfigHistorysRequ)(nil), "proto.GetAppConfigHistorysRequ")
	proto.RegisterType((*GetAppConfigHistorysResp)(nil), "proto.GetAppConfigHistorysResp")
	proto.RegisterType((*RollbackConfigRequ)(nil), "proto.RollbackConfigRequ")
	proto.RegisterType((*RollbackConfigResp)(nil), "proto.RollbackConfigResp")
	proto.RegisterType((*PublicConfigRequ)(nil), "proto.PublicConfigRequ")
	proto.RegisterType((*PublicConfigResp)(nil), "proto.PublicConfigResp")
	proto.RegisterType((*AppConfig)(nil), "proto.AppConfig")
	proto.RegisterType((*AppConfigHistory)(nil), "proto.AppConfigHistory")
}

func init() {
	proto.RegisterFile("config.proto", fileDescriptor_3eaf2c85e69e9ea4)
}

var fileDescriptor_3eaf2c85e69e9ea4 = []byte{
	// 699 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0xfe, 0x39, 0xff, 0x9a, 0x4c, 0xf2, 0xa3, 0xe9, 0x12, 0xc1, 0xe2, 0x0b, 0x91, 0x4f, 0x3d,
	0x50, 0x07, 0x95, 0x13, 0x17, 0x04, 0xad, 0xaa, 0xb6, 0x42, 0x42, 0xc8, 0x88, 0x0b, 0x17, 0xe4,
	0x38, 0x4b, 0x08, 0x8d, 0xbd, 0x26, 0x6b, 0x57, 0xaa, 0xc4, 0x23, 0x20, 0x71, 0x41, 0xe2, 0x51,
	0x78, 0x2b, 0x9e, 0x01, 0xed, 0xd8, 0x5e, 0x27, 0xf6, 0x3a, 0xc5, 0x40, 0xb9, 0x24, 0x9e, 0xf9,
	0x66, 0xbf, 0x99, 0xfd, 0x76, 0x77, 0x76, 0x61, 0xe0, 0xf1, 0xe0, 0xdd, 0x62, 0x6e, 0x87, 0x2b,
	0x1e, 0x71, 0xd2, 0xc6, 0x3f, 0xf3, 0xc9, 0x7c, 0x11, 0xbd, 0x8f, 0xa7, 0xb6, 0xc7, 0xfd, 0xc9,
	0x9c, 0x2f, 0xdd, 0x60, 0xce, 0x6d, 0x2f, 0x90, 0x9f, 0x33, 0x16, 0x1c, 0xc8, 0x11, 0x13, 0xf9,
	0x73, 0x80, 0xd1, 0x13, 0x8f, 0xfb, 0x3e, 0x0f, 0x26, 0x53, 0x57, 0xb0, 0x84, 0xc6, 0xec, 0xbb,
	0x33, 0x7f, 0x11, 0x24, 0x86, 0xf5, 0x16, 0xfe, 0x3f, 0x65, 0xd1, 0x31, 0xa6, 0x71, 0xd8, 0xc7,
	0x98, 0x3c, 0x80, 0xae, 0x8c, 0x95, 0xdf, 0xd4, 0x18, 0x1b, 0xfb, 0xfd, 0xc3, 0xa1, 0x9d, 0x70,
	0xd8, 0x99, 0xdf, 0x51, 0x11, 0x64, 0x0c, 0x7d, 0x37, 0x0c, 0x93, 0xe1, 0xe7, 0x33, 0xda, 0x18,
	0x1b, 0xfb, 0x4d, 0x67, 0xdd, 0x65, 0xf9, 0x1b, 0x09, 0x44, 0x98, 0x27, 0x10, 0xa1, 0x3e, 0x81,
	0x08, 0x1d, 0x15, 0x41, 0x6c, 0xe8, 0x29, 0x36, 0xa4, 0x97, 0xe1, 0x58, 0xba, 0xfd, 0x2c, 0xf3,
	0x3b, 0x79, 0x88, 0xf5, 0xcd, 0x80, 0xbd, 0x53, 0x16, 0x29, 0x4c, 0xfc, 0xc6, 0xa4, 0x86, 0xd0,
	0xbc, 0x60, 0x57, 0x98, 0xad, 0xe7, 0xc8, 0x4f, 0x42, 0x61, 0x07, 0x53, 0xcc, 0x18, 0x6d, 0xa2,
	0x37, 0x33, 0xc9, 0x3e, 0xec, 0xb2, 0xe0, 0x72, 0xb1, 0xe2, 0x81, 0xcf, 0x82, 0xe8, 0x85, 0xeb,
	0x33, 0xda, 0xc2, 0x88, 0xa2, 0xdb, 0x12, 0xa5, 0xc2, 0x6a, 0x8b, 0xf1, 0x10, 0x40, 0xcd, 0x54,
	0xd0, 0xc6, 0xb8, 0xa9, 0x55, 0x63, 0x2d, 0xc6, 0x12, 0x70, 0xfb, 0x78, 0xc5, 0xdc, 0x88, 0xe5,
	0x70, 0x7d, 0x3d, 0xea, 0xae, 0xc1, 0xb1, 0x26, 0x69, 0xdd, 0xb9, 0xca, 0xca, 0x5f, 0x87, 0xb3,
	0x7f, 0x5f, 0x79, 0x29, 0x69, 0xed, 0xca, 0x3f, 0x00, 0x5d, 0x5f, 0xe8, 0xb3, 0x85, 0x88, 0xf8,
	0xea, 0x4a, 0xdc, 0xc8, 0xe9, 0xfa, 0x62, 0x54, 0x25, 0xab, 0xbd, 0xb9, 0x4e, 0x60, 0xcf, 0x2d,
	0xd2, 0xa4, 0x7b, 0xec, 0x6e, 0x51, 0xb3, 0x14, 0x77, 0xca, 0x23, 0xac, 0xcf, 0x06, 0x10, 0x87,
	0x2f, 0x97, 0x53, 0xd7, 0xbb, 0xf8, 0x83, 0x75, 0x23, 0x45, 0x66, 0x35, 0x7f, 0x0d, 0x82, 0xe7,
	0x53, 0x36, 0xb5, 0xf3, 0x19, 0x9e, 0xcf, 0xa6, 0x93, 0x99, 0xd6, 0x51, 0xb9, 0x9a, 0xda, 0x0b,
	0xfa, 0x09, 0x86, 0x2f, 0xe3, 0xe9, 0x72, 0xe1, 0xdd, 0x5c, 0x9b, 0xdc, 0x32, 0x83, 0xa7, 0xc5,
	0xec, 0xb5, 0xeb, 0xff, 0xde, 0x80, 0x9e, 0x5a, 0xba, 0x62, 0x2d, 0x46, 0xb9, 0x96, 0x11, 0xb4,
	0xdd, 0x30, 0x54, 0x75, 0x26, 0xc6, 0xdf, 0xe8, 0x81, 0x59, 0x67, 0x6d, 0xe7, 0x9d, 0x75, 0x04,
	0xed, 0x4b, 0x77, 0x19, 0x33, 0xda, 0x41, 0x5f, 0x62, 0x90, 0x3b, 0xd0, 0x11, 0x91, 0x1b, 0xc5,
	0x82, 0xee, 0x60, 0x09, 0xa9, 0x45, 0x08, 0xb4, 0x7c, 0xe6, 0x73, 0xda, 0xc5, 0x60, 0xfc, 0x26,
	0x16, 0xb4, 0x51, 0x2a, 0xda, 0x43, 0x21, 0x06, 0xd9, 0x5e, 0x95, 0x3e, 0x27, 0x81, 0x88, 0x09,
	0x5d, 0x2f, 0xe9, 0x48, 0x11, 0x05, 0x64, 0x54, 0xb6, 0xc4, 0xe2, 0xe4, 0xcc, 0x47, 0xb4, 0x9f,
	0x60, 0x99, 0x6d, 0xfd, 0x68, 0xc0, 0xb0, 0xb8, 0xe9, 0x2b, 0x36, 0xa7, 0x51, 0xb9, 0x39, 0xaf,
	0x5f, 0x7c, 0x25, 0x78, 0xb3, 0x42, 0xf0, 0xd6, 0xb5, 0x82, 0xb7, 0xb7, 0x0a, 0xde, 0xd1, 0x08,
	0xbe, 0xa3, 0x17, 0xbc, 0xab, 0x15, 0xbc, 0xa7, 0x13, 0x1c, 0x7e, 0x4d, 0xf0, 0xfe, 0x16, 0xc1,
	0x07, 0x9b, 0x82, 0x1f, 0x7e, 0x6d, 0xc1, 0x20, 0x91, 0xe5, 0x15, 0x5b, 0x5d, 0xb2, 0x15, 0x79,
	0x0c, 0x3d, 0xf5, 0x7c, 0x20, 0xa3, 0x34, 0xd5, 0xc6, 0x8b, 0xc5, 0xd4, 0x78, 0x45, 0x68, 0xfd,
	0x47, 0x4e, 0xf0, 0xe5, 0x91, 0x5f, 0xb8, 0x84, 0xe6, 0x81, 0x9b, 0xef, 0x03, 0xb3, 0x02, 0x41,
	0x9a, 0xe7, 0xb0, 0x5b, 0xb8, 0xcd, 0x88, 0x99, 0x86, 0x6b, 0xae, 0x56, 0xb3, 0x12, 0xcb, 0xc8,
	0x0a, 0x17, 0x8c, 0x22, 0xd3, 0xdc, 0x76, 0x66, 0x25, 0x86, 0x64, 0x6f, 0x60, 0xa4, 0xeb, 0xfd,
	0xe4, 0xbe, 0x66, 0x36, 0xeb, 0xb7, 0x90, 0xb9, 0x3d, 0x00, 0xb9, 0xcf, 0xe0, 0xd6, 0x66, 0xdf,
	0x24, 0xf7, 0xd2, 0x41, 0xe5, 0xe6, 0x6e, 0x56, 0x41, 0xc8, 0x74, 0x04, 0x83, 0xf5, 0xfe, 0x45,
	0xb2, 0xcb, 0xa4, 0xd8, 0x52, 0x4d, 0x3d, 0x20, 0x39, 0xa6, 0x1d, 0x44, 0x1e, 0xfd, 0x0c, 0x00,
	0x00, 0xff, 0xff, 0xee, 0x1c, 0xa0, 0xf9, 0x10, 0x0b, 0x00, 0x00,
}
