// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BaseRequ struct {
	PageIndex            int64    `protobuf:"varint,1,opt,name=pageIndex,proto3" json:"pageIndex,omitempty"`
	PageSize             int64    `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseRequ) Reset()         { *m = BaseRequ{} }
func (m *BaseRequ) String() string { return proto.CompactTextString(m) }
func (*BaseRequ) ProtoMessage()    {}
func (*BaseRequ) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{0}
}

func (m *BaseRequ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseRequ.Unmarshal(m, b)
}
func (m *BaseRequ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseRequ.Marshal(b, m, deterministic)
}
func (m *BaseRequ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseRequ.Merge(m, src)
}
func (m *BaseRequ) XXX_Size() int {
	return xxx_messageInfo_BaseRequ.Size(m)
}
func (m *BaseRequ) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseRequ.DiscardUnknown(m)
}

var xxx_messageInfo_BaseRequ proto.InternalMessageInfo

func (m *BaseRequ) GetPageIndex() int64 {
	if m != nil {
		return m.PageIndex
	}
	return 0
}

func (m *BaseRequ) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type BaseResp struct {
	IsSuccess            bool     `protobuf:"varint,1,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	TotalCount           int64    `protobuf:"varint,3,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseResp) Reset()         { *m = BaseResp{} }
func (m *BaseResp) String() string { return proto.CompactTextString(m) }
func (*BaseResp) ProtoMessage()    {}
func (*BaseResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{1}
}

func (m *BaseResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseResp.Unmarshal(m, b)
}
func (m *BaseResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseResp.Marshal(b, m, deterministic)
}
func (m *BaseResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseResp.Merge(m, src)
}
func (m *BaseResp) XXX_Size() int {
	return xxx_messageInfo_BaseResp.Size(m)
}
func (m *BaseResp) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseResp.DiscardUnknown(m)
}

var xxx_messageInfo_BaseResp proto.InternalMessageInfo

func (m *BaseResp) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

func (m *BaseResp) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *BaseResp) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func init() {
	proto.RegisterType((*BaseRequ)(nil), "common.baseRequ")
	proto.RegisterType((*BaseResp)(nil), "common.baseResp")
}

func init() {
	proto.RegisterFile("base.proto", fileDescriptor_db1b6b0986796150)
}

var fileDescriptor_db1b6b0986796150 = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4a, 0x2c, 0x4e,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4b, 0xce, 0xcf, 0xcd, 0xcd, 0xcf, 0x53, 0x72,
	0xe1, 0xe2, 0x00, 0x89, 0x06, 0xa5, 0x16, 0x96, 0x0a, 0xc9, 0x70, 0x71, 0x16, 0x24, 0xa6, 0xa7,
	0x7a, 0xe6, 0xa5, 0xa4, 0x56, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x30, 0x07, 0x21, 0x04, 0x84, 0xa4,
	0xb8, 0x38, 0x40, 0x9c, 0xe0, 0xcc, 0xaa, 0x54, 0x09, 0x26, 0xb0, 0x24, 0x9c, 0xaf, 0x94, 0x03,
	0x33, 0xa5, 0xb8, 0x00, 0x64, 0x4a, 0x66, 0x71, 0x70, 0x69, 0x72, 0x72, 0x6a, 0x71, 0x31, 0xd8,
	0x14, 0x8e, 0x20, 0x84, 0x80, 0x90, 0x12, 0x17, 0x4f, 0x6a, 0x51, 0x51, 0x7e, 0x91, 0x6f, 0x6a,
	0x71, 0x71, 0x62, 0x3a, 0xc4, 0x24, 0xce, 0x20, 0x14, 0x31, 0x21, 0x39, 0x2e, 0xae, 0x92, 0xfc,
	0x92, 0xc4, 0x1c, 0xe7, 0xfc, 0xd2, 0xbc, 0x12, 0x09, 0x66, 0xb0, 0x5d, 0x48, 0x22, 0x49, 0x6c,
	0x60, 0x2f, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x37, 0x27, 0x9e, 0xb2, 0xd0, 0x00, 0x00,
	0x00,
}
